### ISSUE TITLE
environment variables given to overcast is not exposed to remote command run

### ISSUE THREAD

**Issue by hkumarmk** [aaSemble/python-aasemble.deployment#18]
I tried to use below overcast.yaml file
```
undercloud:
  - shell:
      cmd: "/tmp/a.sh ${BUILD_NUMBER}"
  - shell:
      type: remote
      node: uc1
      cmd: "/tmp/a.sh ${BUILD_NUMBER}"
      retry-if-fails: true
      retry-for: 20m
      retry-wait: 5s
```
Here is the content for a.sh which is present on both the remote and local node

echo "`date` $1" >>  /tmp/a.out

HEre is the result on local node (content in /tmp/a.out)

Tue Jul 14 09:42:25 UTC 2015 1507140942

here is the result on remote node (there is no $BUILD_NUMBER printed in output file)

Tue Jul 14 09:41:36 UTC 2015 

It seems the variable is not gettting extracted from local machine.
